name: Hola Mundo
on: [push]

jobs: 
    hola:
        runs-on: ubuntu-latest

        steps:
        - name: Hola Mundo
          run: echo "Hola Mundo Prueba"        
        - name: Crear archivo
          run: touch hola.txt        
        - name: Setear Texto
          run: echo "Hola Mundo" >> hola.txt
        - name: Muestre el texto
          run: cat hola.txt
         
    
    other:
        runs-on: ubuntu-latest

        steps:
        - name: LS
          run: ls -al